version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: andres            # Define el nombre de usuario
      POSTGRES_PASSWORD: 1004           # Define la contraseña del usuario
      POSTGRES_DB: lugares              # Define el nombre de la base de datos
    container_name: bdLugares
    volumes:
      - ./postgres:/var/lib/postgresql/data
